# Generated by Django 2.2.28 on 2025-01-12 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_jobexecution'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrecords',
            name='dob',
            field=models.DateField(null=True, blank=True), 
        ),
    ]
