# Generated by Django 2.2.28 on 2025-01-12 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_userrecords_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrecords',
            name='dob',
            field=models.DateField(null=True, blank=True),
        ),
    ]
